### ISSUE TITLE
Main.js

### ISSUE THREAD

**Issue by Crazygird** [thegreatestgiant/cdn#1]
How do I run main.js?

**Comment by thegreatestgiant** [comment]
you can use this bookmarklet

javascript:var vaporwindow='new Nightmare({"title":"ALL BOOKMARKLETS","type":"js","js":"https://cdn.jsdelivr.net/gh/thegreatestgiant/cdn@main/Main.js","theme": "dark"\n})';async function injectnightmare(){var e=await fetch("https://cdn.jsdelivr.net/gh/FogNetwork/Nightmare-Windows/windows.min.js"),n=await e.text();n=n.replaceAll("<br>",";");var t=document.createElement("script");t.innerHTML=n+"\neval("+vaporwindow+")",document.getElementsByTagName("html")[0].appendChild(t)}var cdn2=document.createElement("link");cdn2.setAttribute("rel","stylesheet"),cdn2.href="https://cdn.jsdelivr.net/gh/FogNetwork/Nightmare-Windows/windows.css",document.getElementsByTagName("html")[0].appendChild(cdn2),injectnightmare()

**Comment by Crazygird** [comment]
ok cool

**Comment by Crazygird** [comment]
it doesn't work
